# Generated by Django 5.0.1 on 2024-05-27 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Combination",
            fields=[
                ("comb_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "first_col",
                    models.CharField(
                        help_text="Enter a valid hex color code (e.g., #FFFFFF).",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color code.",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "sec_col",
                    models.CharField(
                        help_text="Enter a valid hex color code (e.g., #FFFFFF).",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color code.",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "angle",
                    models.IntegerField(
                        help_text="Enter an integer angle between 0 and 360 degrees.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(360),
                        ],
                    ),
                ),
            ],
        ),
    ]
