# Generated by Django 5.0.1 on 2024-05-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_userauthdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="combination",
            name="username",
            field=models.CharField(default=None, max_length=20),
        ),
    ]
