# Generated by Django 5.0.1 on 2024-05-28 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_remove_combination_username_combination_my_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="combination",
            name="angle",
        ),
    ]
